{% set name = "dict2css" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dict2css-{{ version }}.tar.gz
  sha256: fc30e9feca9996db5cf5f3a5fb46e6506a293950aa2cba62df7413440bcc1a67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - whey >=0.0.20
  run:
    - cssutils <=2.11.0,>=2.2.0
    - domdf-python-tools >=2.2.0
    - python >={{ python_min }}

test:
  imports:
    - dict2css
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sphinx-toolbox/dict2css
  summary: A μ-library for constructing cascading style sheets from Python dictionaries.
  license: MIT
  license_file: LICENSE
  doc_url: https://dict2css.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
